pipelines:
  - name: test_ssh
    configuration:
      environmentVariables:
        readOnly:
          envVarNpmRepo: avengers-npm
          envVarGenericRepo: avengers-generic
          envVarGenericPromoteRepo: avengers-rc-generic-local
    steps:
      - name: deploy_to_minion
        type: Bash
        configuration:
          integration:
            - name: access_minion
        execution:
          onStart:
            - echo onStart
          onExecute:
            - ssh -i ${int_access_minion_sshKey_privateKey} 10.41.0.57 whoami
            - ssh -i ${int_access_minion_sshKey_privateKey} 10.41.0.57 "uname -a"