pipelines:
  - name: test_ssh
    configuration:
      environmentVariables:
        readOnly:
          envVarNpmRepo: avengers-npm
          envVarGenericRepo: avengers-generic
          envVarGenericPromoteRepo: avengers-rc-generic-local
    steps:
      - name: deploy_to_minion
        type: Bash
        configuration:
          inputResources:
            - name: access_minion
            - name: update_prop
        execution:
          onStart:
            - echo onStart
            - echo "$res_update_prop_payload" | jq '.' > payload.json
            - cat payload.json
          onExecute:
            - ssh -i ~/.ssh/access_minion yannc@${res_access_minion_targets_0} "uname -a"
