pipelines:
  - name: test_ssh
    configuration:
      environmentVariables:
        readOnly:
          envVarNpmRepo: avengers-npm
          envVarGenericRepo: avengers-generic
          envVarGenericPromoteRepo: avengers-rc-generic-local
    steps:
      - name: deploy_to_minion
        type: Bash
        configuration:
          integrations:
            - name: minion
        execution:
          onStart:
            - echo onStart
          onExecute:
            - ssh 10.41.0.57 whoami
            - echo  ${int_minion_sshKey_privateKey}