pipelines:
  - name: test_cleanup
    steps:
      - name: apply_cleanup
        type: cleanup/Artifact
        configuration:
          dryRun: false
          inputResources:
            - name: my_cleanup_policies
            - name: my_cron
          integrations:
            - name: artifactory_eu
        execution:
          onStart:
            - jfrog rt c show && jfrog --version
