apiVersion: v1.1
pipelines:
  - name: test_extension 
    steps:
      - name: init
        type: Bash
        configuration:
          integrations:
            - name: artifactory_eu
          inputResources:
            - name: src_code_test_ext
        execution:
          onStart:
            - echo truc
          onExecute:
            - echo salut
      - name: package_app
        type: PkgDebian
#        syntaxVersion: 1.0.0
        configuration:
#          binaryLocation: /toto/tutu
          binaryArtifactoryLocation: "**/multi-module-application*.jar"
          buildName: backapp_mvn
          buildNumber: 2
          appExtension: "jar"
          debianBuildName: "my-super-build"
          targetDebianRepo: "ninja-debian-release"
          integrations:
            - name: artifactory_eu
          inputSteps:
            - name: init
        # execution:
        #   onStart:
        #     - echo test
        #   onExecute:
        #     - echo test test test