apiVersion: v1.1
pipelines:
  - name: test_extension 
    steps:
      - name: init
        type: Bash
        configuration:
          integrations:
            - name: artifactory_eu
          inputResources:
            - name: src_code_test_ext
        execution:
          onStart:
            - echo truc
          onExecute:
            - echo salut
      - name: package_app
        type: PackageDebian
        configuration:
          binaryLocation: /toto/tutu
          integrations:
            - name: artifactory_eu
          inputSteps:
            - name: init
        execution:
          onStart:
            - echo test
          onExecute:
            - echo test test test