apiVersion: v1.1
pipelines:
  - name: promote_pipeline
    steps:
      - name: promotion_to_UAT 
        type: PromoteBuild 
        configuration:
          targetRepository: avengers-generic-uat-local
          includeDependencies: false
          status: "SIT_OK"
          comment: "Passed SIT test"
          copy: false
          inputResources:
            - name: App_BuildInfo 
          outputResources:
            - name: App_BuildInfo_SIT_ok 
        execution:
          onSuccess:
            - echo "Passed SIT test" 
      - name: promotion_to_prod 
        type: PromoteBuild 
        configuration:
          targetRepository: avengers-generic-prod-local
          includeDependencies: false
          status: "Production"
          comment: "Passed UAT test"
          copy: false
          inputResources:
            - name: App_BuildInfo_SIT_ok 
          outputResources:
            - name: App_BuildInfo_Prod_ok 
        execution:
          onSuccess:
            - echo "Passed UAT test" 
