apiVersion: v1.1
pipelines:
  - name: promote_pipeline
    steps:
      - name: promotion_to_UAT 
        type: PromoteBuild 
        configuration:
          targetRepository: avengers-generic-uat-local
          includeDependencies: false
          status: "SIT_OK"
          comment: "Passed SIT test"
          copy: false
          inputResources:
            - name: myApp_BuildInfo 
          outputResources:
            - name: myApp_BuildInfo_SIT_ok 
        execution:
          onSuccess:
            - echo "Passed SIT test" 
      - name: promotion_to_prod 
        type: PromoteBuild 
        configuration:
          targetRepository: avengers-generic-prod-local
          includeDependencies: false
          status: "Production"
          comment: "Passed UAT test"
          copy: false
          inputResources:
            - name: myApp_BuildInfo_SIT_ok 
          outputResources:
            - name: myApp_BuildInfo_Prod_ok 
        execution:
          onSuccess:
            - echo "Passed UAT test" 
      - name: init_release_bundle_test
        type: CreateReleaseBundle 
        configuration:
          releaseBundleName: myApp 
          releaseBundleVersion: 0.0.3 
          dryRun: false
          sign: true 
          description: automatic creation 
          releaseNotes:
            syntax: markdown
            content: |
              # Description 
              super release 
              * Feature 1 
              * Bigfix 1
          inputResources:
            - name: myApp_BuildInfo_Prod_ok 
          outputResources:
            - name: conanRB 
      - name: distribute_test
        type: DistributeReleaseBundle
        configuration:
          dryRun: false 
          inputResources:
            - name: conanRB 
              trigger: true   
            - name: myApp_distributionRule_test
#              trigger: false    # default true
