pipelines:
  - name: k8s_frontapp_npm
    configuration:
      environmentVariables:
        readOnly:
          envVarNpmRepo: avengers-npm
          envVarGenericRepo: avengers-generic
          envVarGenericPromoteRepo: avengers-rc-generic-local
    steps:
      - name: my_action
        type: Bash
        configuration:
          inputResources:
            - name: update-prop
        execution:
          onStart:
            - echo onStart
          onExecute:
            - echo "$res_update-prop_payload" | jq '.' > payload.json
            - read_json payload.json "LESSER_SECRET_FORMULA"