pipelines:
  - name: test_matrix
    steps:
      - name: pre_matrix
        type: PreMatrix
        configuration:
          inputResources:
            - name: src_greeting_lib
          integrations:
            - name: my_github
        #     - name: artifactory_eu
        execution:
          onExecute:
            - echo "pulled code"
        #     - conan remote add art1 ${int_artifactory_eu_url}/api/conan/urs-conan
        #     - conan user -p ${res_artifactory_eu_apikey} -r art1 ${int_artifactory_eu_user}
        #     - conan remote list
      - name: matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: pre_matrix
          integrations:
            - name: my_github
            - name: artifactory_eu
        stepletMultipliers:
          environmentVariables: 
            - build_type: Release 
              shared:     true
            - build_type: Debug 
              shared:     true
          runtimes:
            - type: image
              image:
                custom:
                  name: conanio/gcc9
                  tag: 1.36.0         
            - type: image
              image:
                custom:
                  name: conanio/clang60
                  tag: 1.35.1   
          fastFail: false          # default false.
          # allowFailures:             # optional, array of combinations
          #   # - nodePool:              # that are allowed to fail 
          #   - environmentVariables:
          #       animal:    goat               # - Set 2
          #       mineral:   iron
          #       vegetable: broccoli
          #     runtime:              
          #       type: image
          #       image:
          #         auto:
          #           language: java
          #           versions:
          #             - 15 
          # exclude:                   # optional, array of combinations that are not executed 
          #   # - nodePool:              
          #   - environmentVariables:
          #       animal:    goat               # - Set 2
          #       mineral:   iron
          #       vegetable: broccoli
          #     runtime:
          #       type: image
          #       image:
          #         auto:
          #           language: go
          #           versions:
          #             - 1.15.2
        execution:
          onStart:
            - conan remote add art1 ${int_artifactory_eu_url}/api/conan/urs-conan
            - conan user -p ${res_artifactory_eu_apikey} -r art1 ${int_artifactory_eu_user}
            - conan remote list
          onExecute:
            - pwd 
            - cd pre_matrix/dependencyState/resources/src_greeting_lib
            - ls -l 
            - cd Greeting
            - conan profile new --detect default
            - conan profile show default
            - conan create . greeting/1.0.0@cyan21/test 
            - conan upload "greeting*" -r art1
