pipelines:
  - name: test_matrix
    steps:
      - name: pre_matrix
        type: PreMatrix
        # configuration:
        #   inputResources:
        #     - my_cron
        execution:
          onStart:
            - echo "Starting up"
          onExecute:
            - echo "Execute"
      - name: matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: matrix_fan_out_example
        stepletMultipliers:
          environmentVariables: 
            - animal:    dog                # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat               # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
          runtimes:                         # Runtimes for steplets
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 15          
            - type: image
              image:
                auto:
                  language: go
                  versions:
                    - 1.15.2
          fastFail: false          # default false.
          allowFailures:             # optional, array of combinations
            # - nodePool:              # that are allowed to fail 
            - environmentVariables:
                animal:    goat               # - Set 2
                mineral:   iron
                vegetable: broccoli
              runtime:              
                type: image
                image:
                  auto:
                    language: java
                    versions:
                      - 15 
          exclude:                   # optional, array of combinations that are not executed 
            # - nodePool:              
            - environmentVariables:
                animal:    goat               # - Set 2
                mineral:   iron
                vegetable: broccoli
              runtime:
                type: image
                image:
                  auto:
                    language: go
                    versions:
                      - 1.15.2
        execution:
          onExecute:
            - echo "I am executing matrix steplet ${steplet_id}"
            - echo "Envs animal= $animal , mineral = $mineral , vegetable = $vegetable"
            - >
              echo "Runtime image name\: $step_image_name | Runtime image tag\: $step_image_tag"
            - if [ $animal == "goat" ];then exit 1; fi
            - sleep 60

