pipelines:
  - name: test_matrix
    steps:
      - name: matrix_fan_out_example
        type: Bash
        # configuration:
        #   inputResources:
        #     - my_cron
        execution:
          onStart:
            - echo "Starting up"
          onExecute:
            - echo "Execute"
      - name: matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: matrix_fan_out_example
        stepletMultipliers:
          environmentVariables: 
            - animal:    dog                # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat               # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
      
          runtimes:                         # Runtimes for steplets
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 15
                    
            - type: image
              image:
                auto:
                  language: go
                  versions:
                    - 1.15.2
        execution:
          onExecute:
            - echo "I am executing matrix steplet ${steplet_id}"
            - echo "Envs animal= $animal , mineral = $mineral , vegetable = $vegetable"
            - >
              echo "Runtime image name\: $step_image_name | Runtime image tag\: $step_image_tag"
