pipelines:
  - name: test_deployment
    steps:
      - name: deploy_webapp
        type: deployment/Webapp
        configuration:
          technology: java
          appServer: jboss
          ansible:
            role: wildfly
            inventory: uat
          inputResources:
            # - name: my_cron
            - name: vm_group1
            - name: wh_jenkins1
          integrations:
            - name: artifactory_eu
        execution:
          onStart:
            - jfrog rt c show && jfrog --version
