template: true   # required for local templates.
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: ych_github_pipe # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: cyan21/test-pipelines # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: master


pipelines:
    - name: HealthCheck
      configuration:
        jfrogCliVersion: 2
      steps:
  #Ping instances
#         - name: Ping
#           type: Bash
#           configuration:
#             integrations:
#               - name: [yann_platform_token yannsbx_platform_access]
#           execution:
#             onStart:
#               - echo [yann_platform_token yannsbx_platform_access]
#               - configure_jfrog_cli --artifactory-url "${int_[yann_platform_token yannsbx_platform_access]_url}/artifactory" --access-token "${int_[yann_platform_token yannsbx_platform_access]_accessToken}" --server-name psemea
# #              - configure_jfrog_cli --artifactory-url ${int_yann_platform_token_url}/artifactory --access-token ${int_yann_platform_token_accessToken} --server-name psemea
#             onExecute:
#               - | 
#                 for i in 1 2 3; do 
#                     echo "[INFO] iteration $i ..."
#                     jf rt ping --server-id psemea
#                     sleep 5
#                 done
        # - name: Ping_2
        #   type: utils/ping
        #   configuration:
        #     affinityGroup: together
        #     integrations:
        #
        #       - name: "yann_platform_token"
        #
        #       - name: "yannsbx_platform_access"
        #
        #     iteration: 2
        #     sleepBetweenIteration: 5
        - name: Update_status_yml
          type: Bash
          configuration:
            affinityGroup: together
            # inputSteps:
            #   - name: Ping_2
            # integrations:
            #
            #   - name: "yann_platform_token"
            #
            #   - name: "yannsbx_platform_access"
            #
              # - name: artifactory_eu
          execution:
            onStart:
              - echo yannsbx_platform_access 
              # - configure_jfrog_cli --artifactory-url "${int_[yann_platform_token yannsbx_platform_access]_url}/artifactory" --access-token "${int_[yann_platform_token yannsbx_platform_access]_accessToken}" --server-name psemea
              # - jf -v
              # - jf c s
            # onExecute:
            #   - | 
            #     for i in 1 2 3; do 
            #         echo "[INFO] iteration $i ..."
            #         jf rt ping --server-id psemea
            #         sleep 5
            #     done
 