pipelines:
  - name: python_pipeline
    configuration:
      environmentVariables:
        readOnly:
          art_url: http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory
          art_repo: asgardian-pypi
          art_repo_promotion: asgardian-pypi-prod-local
    steps:
      - name: python_docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: . 
          dockerFileName: CI/DockerBuild/Dockerfile
          dockerImageName: docker-dev-local.artifactory-eu.soleng-emea-staging.jfrog.team/python-build
          dockerImageTag: ${run_number}
          dockerOptions: --build-arg BUILD_NAME=python-greeting --build-arg BUILD_NUMBER=${run_number}  --build-arg ARTY_URL=${art_url} --build-arg ARTY_USER=${int_artSecret_user}  --build-arg ARTY_APIKEY=${int_artSecret_apikey} --build-arg ARTY_MAIN_REPO=${art_repo} 
          inputResources:
            - name: python_pipeline_src
          integrations:
            - name: registry_eu
            - name: artSecret

      - name: python_scan
        type: XrayScan
        configuration:
          waitUntilFinish: true
          inputResources:
            - name: python_BuildInfo
              trigger: true
          outputResources: 
            - name: scanned_python_BuildInfo

      - name: python_promote
        type: PromoteBuild
        configuration:
          targetRepository:      ${art_repo_promotion} 
          includeDependencies:   false   
          status:                Passed
          comment:               Artifact passed Xray Scan
          copy:                  false
          inputResources:
            - name:    scanned_python_Build_Info    # optional
              trigger: true       
          outputResources:
            - name: promoted_python_BuildInfo 
