pipelines:
  - name: test_podman
    steps:
      - name: install_podman
        type: Bash
        configuration:
          affinityGroup: together
          runtime:
            type: host
        execution:
          onExecute:
            # - sudo mkdir -p /etc/docker 
            # - > 
            #   sudo jq -n  "{\"insecure-registries\": [\"${envVarDockerRepoUrl}\"]}" > /etc/docker/daemon.json
            # - sudo systemctl restart docker
            # - sudo cat /etc/docker/daemon.json
            - echo ${operating_system}
            - echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${operating_system}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
            - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${operating_system}/Release.key | sudo apt-key add -
            - sudo apt update && sudo apt -y install podman
            - podman info
            - cli_path=$(dirname "$(which jfrog)") && curl -fL https://getcli.jfrog.io | sh &&  mv ./jfrog "$cli_path/" && ls -l "$cli_path/jfrog"  && jfrog --version

